micronaut:
  application:
    name: employeeManagement

datasources:
  default:
    url: jdbc:mysql://localhost:3306/classicmodels
    driverClassName: com.mysql.jdbc.Driver
    username: deepak
    password: Mysql@123

jpa:
  default:
#    packages-to-scan:
#      - 'com.poc.micronaut.empmgmt'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true